### ISSUE TITLE
Test all links on site

### ISSUE THREAD

**Issue by timskovjacobsen** [timskovjacobsen/steelprofiles_api#6]
* Use pytest as testing framework
* Test(s) should verify that all links on [steelapi.timskovjabosen.com](https://steelapi.timskovjacobsen.com/) actually work.
 There are no implementation requirements apart from using pytest.

**Comment by ry-v1** [comment]
@timskovjacobsen - May I try?

**Comment by timskovjacobsen** [comment]
> 
> 
> @timskovjacobsen - May I try?

Of course, give it a go :)! Let me know if you have any questions!

**Comment by ry-v1** [comment]
> > @timskovjacobsen - May I try?
> 
> Of course, give it a go :)! Let me know if you have any questions!

Submitted a pull request #12 . Please check
