### ISSUE TITLE
Improve design of front page

### ISSUE THREAD

**Issue by timskovjacobsen** [timskovjacobsen/steelprofiles_api#7]
Right now, the [front page](https://steelapi.timskovjacobsen.com/) is just "thrown" in there and it could you a better design

Requirements to changes:

* The front page should not be longer than a couple of page scrolls, and should give a quick overview of the things that are currently listed
* Design should be minimalistic
* Other than that, choice of design, fonts, icons, etc. is up to the contributor

**Comment by vczoika** [comment]
May I work in this issue? Thank you in advance!

**Comment by timskovjacobsen** [comment]
> May I work in this issue? Thank you in advance!

Yes, of course, thanks!

Let me know if you need any help getting started. There currently are no instructions written down as to how to get the app running locally.

**Comment by saiteja-2731** [comment]
Can I work on this issue?

**Comment by timskovjacobsen** [comment]
> 
> 
> Can I work on this issue?

I assigned @vczoika, if you find some other value to add we can create an issue for that.

**Comment by timskovjacobsen** [comment]
Closed by PR #11
