### ISSUE TITLE
Improve the look and functionality of profile tables

### ISSUE THREAD

**Issue by timskovjacobsen** [timskovjacobsen/steelprofiles_api#8]
Make tables that are better looking than the current ones: Example of current: https://steelapi.timskovjacobsen.com/HEA

Changes made are up to the contributor. As long as it improves the "static" design that is currently there.

These are just some ideas, but do not have to be implemented:
* highlight row on hover
* enable for rows to be copied
* enable for cell values to be copied

**Comment by Athi223** [comment]
I would like to contribute to this, could you assign it to me?

**Comment by timskovjacobsen** [comment]
> 
> 
> I would like to contribute to this, could you assign it to me?

Sure, thank you!

**Comment by timskovjacobsen** [comment]
Solved by PR #9
